Script started on Thu 24 Jan 2019 09:38:37 PM CST
[?1034hbash-4.2$ pwd
/home/u2/swd0008/COMP_2710/Project_1
bash-4.2$ ls
a.out  commands.script	simple	simple2.cpp  Spencer_Downey.tar.gz  typescript	wrong
bash-4.2$ mkdir directory
bash-4.2$ ls
a.out  commands.script	directory  simple  simple2.cpp	Spencer_Downey.tar.gz  typescript  wrong
bash-4.2$ cp typec[Kscript home[K[K[K[K/home/u2/swd0008/
bash-4.2$ cd swd0008
bash: cd: swd0008: No such file or directory
bash-4.2$ ls swd0008
ls: cannot access swd0008: No such file or directory
bash-4.2$ [Kbash-4.2$ mv [K[K[Kcd ..
bash-4.2$ cd ..
bash-4.2$ ls
a.out	 Application Data  COMP 2210  Desktop	 Documents	ntuser.cmd	     standard  typescript
appdata  COMP 1210	   COMP_2710  directory  factorial.cpp	Spencer Resume.docx  test
bash-4.2$ mv typescript /home/u@[K2/swd0008/pri[K[K[KProject[K[K[K[K[K[K[KCOM_[KP_2710/
bash-4.2$ rm typ[K[K[K[K[K[Kcd COMP_2710/
bash-4.2$ rm typescript 
bash-4.2$ chmod u-[K=rex test
chmod: invalid mode: ‘u=rex’
Try 'chmod --help' for more information.
bash-4.2$ chmod u=rex test[1P[1@w
chmod: cannot access ‘test’: No such file or directory
bash-4.2$ chmod u=rwx test[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kls
helloworld.cpp	Project_1
bash-4.2$ cd ..
bash-4.2$ ls
a.out	 Application Data  COMP 2210  Desktop	 Documents	ntuser.cmd	     standard
appdata  COMP 1210	   COMP_2710  directory  factorial.cpp	Spencer Resume.docx  test
bash-4.2$ lscd ..[3Plschmod u=rwx test[C
bash-4.2$ clear
[3;J[H[2Jbash-4.2$ who
pzr0020  pts/0        2019-01-15 15:35 (ettin.eng.auburn.edu)
twf0001  pts/2        2019-01-24 16:07 (ettin.eng.auburn.edu)
yzt0042  pts/3        2019-01-24 17:21 (ettin.eng.auburn.edu)
swd0008  pts/4        2019-01-24 21:38
lzm0056  pts/7        2019-01-24 21:03 (ettin.eng.auburn.edu)
swd0008  pts/8        2019-01-24 21:03 (ettin.eng.auburn.edu)
bash-4.2$ nproc
16
bash-4.2$ g++ --h
Usage: g++ [options] file...
Options:
  -pass-exit-codes         Exit with highest error code from a phase
  --help                   Display this information
  --target-help            Display target specific command line options
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...]
                           Display specific types of command line options
  (Use '-v --help' to display command line options of sub-processes)
  --version                Display compiler version information
  -dumpspecs               Display all of the built in spec strings
  -dumpversion             Display the version of the compiler
  -dumpmachine             Display the compiler's target processor
  -print-search-dirs       Display the directories in the compiler's search path
  -print-libgcc-file-name  Display the name of the compiler's companion library
  -print-file-name=<lib>   Display the full path to library <lib>
  -print-prog-name=<prog>  Display the full path to compiler component <prog>
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path
  -print-multi-directory   Display the root directory for versions of libgcc
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories
  -print-multi-os-directory Display the relative path to OS libraries
  -print-sysroot           Display the target libraries directory
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers
  -Wa,<options>            Pass comma-separated <options> on to the assembler
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor
  -Wl,<options>            Pass comma-separated <options> on to the linker
  -Xassembler <arg>        Pass <arg> on to the assembler
  -Xpreprocessor <arg>     Pass <arg> on to the preprocessor
  -Xlinker <arg>           Pass <arg> on to the linker
  -save-temps              Do not delete intermediate files
  -save-temps=<arg>        Do not delete intermediate files
  -no-canonical-prefixes   Do not canonicalize paths when building relative
                           prefixes to other gcc components
  -pipe                    Use pipes rather than intermediate files
  -time                    Time the execution of each subprocess
  -specs=<file>            Override built-in specs with the contents of <file>
  -std=<standard>          Assume that the input sources are for <standard>
  --sysroot=<directory>    Use <directory> as the root directory for headers
                           and libraries
  -B <directory>           Add <directory> to the compiler's search paths
  -v                       Display the programs invoked by the compiler
  -###                     Like -v but options quoted and commands not executed
  -E                       Preprocess only; do not compile, assemble or link
  -S                       Compile only; do not assemble or link
  -c                       Compile and assemble, but do not link
  -o <file>                Place the output into <file>
  -pie                     Create a position independent executable
  -shared                  Create a shared library
  -x <language>            Specify the language of the following input files
                           Permissible languages include: c c++ assembler none
                           'none' means revert to the default behavior of
                           guessing the language based on the file's extension

Options starting with -g, -f, -m, -O, -W, or --param are automatically
 passed on to the various sub-processes invoked by g++.  In order to pass
 other options on to these processes the -W<letter> options must be used.

For bug reporting instructions, please see:
<http://bugzilla.redhat.com/bugzilla>.
bash-4.2$ exit
exit

Script done on Thu 24 Jan 2019 09:43:00 PM CST
